# Generated by Django 4.2.16 on 2024-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('subTile', models.TextField()),
                ('myDescription', models.TextField()),
                ('imageDescription', models.ImageField(upload_to='images/')),
                ('titleBenefits', models.CharField(max_length=255)),
            ],
        ),
    ]
