# Generated by Django 4.2.16 on 2024-09-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('detail_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='blogdetails.detailpage')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('detail_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='blogdetails.detailpage')),
            ],
        ),
    ]
