# Generated by Django 4.2.16 on 2024-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdetails', '0002_servicespage_benefitspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
