# Generated by Django 4.2.16 on 2024-09-21 16:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdetails', '0003_detailpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitspage',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
