# Generated by Django 4.2.16 on 2024-09-28 12:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('command', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('recomendation', models.CharField(max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.stepcourse')),
            ],
        ),
    ]
