# Generated by Django 4.2.16 on 2024-09-29 15:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_contentcourse_recomendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcourse',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='contentcourse',
            name='recomendation',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
