# Generated by Django 4.2.16 on 2024-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_contentcourse_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcourse',
            name='recomendation',
            field=models.TextField(),
        ),
    ]
