# Generated by Django 4.2.16 on 2024-09-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_contentcourse_recomendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepcourse',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentcourse',
            name='description',
            field=models.TextField(),
        ),
    ]
