# Generated by Django 4.2.16 on 2024-09-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_stepcourse_position_alter_contentcourse_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepcourse',
            name='position',
        ),
    ]
