# Generated by Django 4.2.16 on 2024-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lear',
            name='command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lear',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lear',
            name='recomendation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lear',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
